// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// connected_components_cpp
IntegerMatrix connected_components_cpp(IntegerMatrix binary_image);
RcppExport SEXP _CaImagingAnalysisFr_connected_components_cpp(SEXP binary_imageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type binary_image(binary_imageSEXP);
    rcpp_result_gen = Rcpp::wrap(connected_components_cpp(binary_image));
    return rcpp_result_gen;
END_RCPP
}
// distance_transform_cpp
NumericMatrix distance_transform_cpp(IntegerMatrix binary_image);
RcppExport SEXP _CaImagingAnalysisFr_distance_transform_cpp(SEXP binary_imageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type binary_image(binary_imageSEXP);
    rcpp_result_gen = Rcpp::wrap(distance_transform_cpp(binary_image));
    return rcpp_result_gen;
END_RCPP
}
// gaussian_blur_cpp
NumericMatrix gaussian_blur_cpp(NumericMatrix image, double sigma);
RcppExport SEXP _CaImagingAnalysisFr_gaussian_blur_cpp(SEXP imageSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type image(imageSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_blur_cpp(image, sigma));
    return rcpp_result_gen;
END_RCPP
}
// extract_trace_cpp
NumericVector extract_trace_cpp(NumericVector movie, NumericMatrix mask, String method);
RcppExport SEXP _CaImagingAnalysisFr_extract_trace_cpp(SEXP movieSEXP, SEXP maskSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type movie(movieSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_trace_cpp(movie, mask, method));
    return rcpp_result_gen;
END_RCPP
}
// local_correlation_cpp
NumericMatrix local_correlation_cpp(NumericVector movie, int radius);
RcppExport SEXP _CaImagingAnalysisFr_local_correlation_cpp(SEXP movieSEXP, SEXP radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type movie(movieSEXP);
    Rcpp::traits::input_parameter< int >::type radius(radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(local_correlation_cpp(movie, radius));
    return rcpp_result_gen;
END_RCPP
}
// median_filter_cpp
NumericMatrix median_filter_cpp(NumericMatrix image, int radius);
RcppExport SEXP _CaImagingAnalysisFr_median_filter_cpp(SEXP imageSEXP, SEXP radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type image(imageSEXP);
    Rcpp::traits::input_parameter< int >::type radius(radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(median_filter_cpp(image, radius));
    return rcpp_result_gen;
END_RCPP
}
// threshold_image_cpp
IntegerMatrix threshold_image_cpp(NumericMatrix image, double threshold, String method);
RcppExport SEXP _CaImagingAnalysisFr_threshold_image_cpp(SEXP imageSEXP, SEXP thresholdSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type image(imageSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(threshold_image_cpp(image, threshold, method));
    return rcpp_result_gen;
END_RCPP
}
// shift_image_cpp
NumericMatrix shift_image_cpp(NumericMatrix image, double shift_x, double shift_y);
RcppExport SEXP _CaImagingAnalysisFr_shift_image_cpp(SEXP imageSEXP, SEXP shift_xSEXP, SEXP shift_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type image(imageSEXP);
    Rcpp::traits::input_parameter< double >::type shift_x(shift_xSEXP);
    Rcpp::traits::input_parameter< double >::type shift_y(shift_ySEXP);
    rcpp_result_gen = Rcpp::wrap(shift_image_cpp(image, shift_x, shift_y));
    return rcpp_result_gen;
END_RCPP
}
// phase_correlation_cpp
NumericVector phase_correlation_cpp(NumericMatrix ref, NumericMatrix target, int max_shift);
RcppExport SEXP _CaImagingAnalysisFr_phase_correlation_cpp(SEXP refSEXP, SEXP targetSEXP, SEXP max_shiftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type ref(refSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type target(targetSEXP);
    Rcpp::traits::input_parameter< int >::type max_shift(max_shiftSEXP);
    rcpp_result_gen = Rcpp::wrap(phase_correlation_cpp(ref, target, max_shift));
    return rcpp_result_gen;
END_RCPP
}
// motion_correct_movie_cpp
List motion_correct_movie_cpp(NumericVector movie, NumericMatrix tmpl, int max_shift);
RcppExport SEXP _CaImagingAnalysisFr_motion_correct_movie_cpp(SEXP movieSEXP, SEXP tmplSEXP, SEXP max_shiftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type movie(movieSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tmpl(tmplSEXP);
    Rcpp::traits::input_parameter< int >::type max_shift(max_shiftSEXP);
    rcpp_result_gen = Rcpp::wrap(motion_correct_movie_cpp(movie, tmpl, max_shift));
    return rcpp_result_gen;
END_RCPP
}
// compute_template_cpp
NumericMatrix compute_template_cpp(NumericVector movie, int n_frames);
RcppExport SEXP _CaImagingAnalysisFr_compute_template_cpp(SEXP movieSEXP, SEXP n_framesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type movie(movieSEXP);
    Rcpp::traits::input_parameter< int >::type n_frames(n_framesSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_template_cpp(movie, n_frames));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CaImagingAnalysisFr_connected_components_cpp", (DL_FUNC) &_CaImagingAnalysisFr_connected_components_cpp, 1},
    {"_CaImagingAnalysisFr_distance_transform_cpp", (DL_FUNC) &_CaImagingAnalysisFr_distance_transform_cpp, 1},
    {"_CaImagingAnalysisFr_gaussian_blur_cpp", (DL_FUNC) &_CaImagingAnalysisFr_gaussian_blur_cpp, 2},
    {"_CaImagingAnalysisFr_extract_trace_cpp", (DL_FUNC) &_CaImagingAnalysisFr_extract_trace_cpp, 3},
    {"_CaImagingAnalysisFr_local_correlation_cpp", (DL_FUNC) &_CaImagingAnalysisFr_local_correlation_cpp, 2},
    {"_CaImagingAnalysisFr_median_filter_cpp", (DL_FUNC) &_CaImagingAnalysisFr_median_filter_cpp, 2},
    {"_CaImagingAnalysisFr_threshold_image_cpp", (DL_FUNC) &_CaImagingAnalysisFr_threshold_image_cpp, 3},
    {"_CaImagingAnalysisFr_shift_image_cpp", (DL_FUNC) &_CaImagingAnalysisFr_shift_image_cpp, 3},
    {"_CaImagingAnalysisFr_phase_correlation_cpp", (DL_FUNC) &_CaImagingAnalysisFr_phase_correlation_cpp, 3},
    {"_CaImagingAnalysisFr_motion_correct_movie_cpp", (DL_FUNC) &_CaImagingAnalysisFr_motion_correct_movie_cpp, 3},
    {"_CaImagingAnalysisFr_compute_template_cpp", (DL_FUNC) &_CaImagingAnalysisFr_compute_template_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_CaImagingAnalysisFr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
