# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Connected components labeling (C++ implementation)
#'
#' Fast 8-connected component labeling using union-find.
#'
#' @param binary_image Binary matrix (0/1)
#'
#' @return Integer matrix with component labels
#' @export
connected_components_cpp <- function(binary_image) {
    .Call(`_CaImagingAnalysisFr_connected_components_cpp`, binary_image)
}

#' Distance transform (C++ implementation)
#'
#' Compute Euclidean distance transform of binary image.
#'
#' @param binary_image Binary matrix (0 = background, >0 = foreground)
#'
#' @return Numeric matrix with distances to nearest background pixel
#' @export
distance_transform_cpp <- function(binary_image) {
    .Call(`_CaImagingAnalysisFr_distance_transform_cpp`, binary_image)
}

#' Gaussian blur (C++ implementation)
#'
#' Fast Gaussian smoothing using separable kernel.
#'
#' @param image Numeric matrix
#' @param sigma Standard deviation of Gaussian kernel
#'
#' @return Smoothed image matrix
#' @export
gaussian_blur_cpp <- function(image, sigma) {
    .Call(`_CaImagingAnalysisFr_gaussian_blur_cpp`, image, sigma)
}

#' Extract trace from ROI mask (C++ implementation)
#'
#' Fast trace extraction using mask.
#'
#' @param movie 3D array (height x width x frames)
#' @param mask Binary mask matrix
#' @param method "mean", "sum", or "weighted"
#'
#' @return Numeric vector of trace values
#' @export
extract_trace_cpp <- function(movie, mask, method = "mean") {
    .Call(`_CaImagingAnalysisFr_extract_trace_cpp`, movie, mask, method)
}

#' Local correlation image (C++ implementation)
#'
#' Compute pixel-wise correlation with neighbors for cell detection.
#'
#' @param movie 3D array (height x width x frames)
#' @param radius Neighborhood radius
#'
#' @return Correlation image matrix
#' @export
local_correlation_cpp <- function(movie, radius = 1L) {
    .Call(`_CaImagingAnalysisFr_local_correlation_cpp`, movie, radius)
}

#' Median filter (C++ implementation)
#'
#' Fast median filtering for image denoising.
#'
#' @param image Numeric matrix
#' @param radius Filter radius
#'
#' @return Filtered image matrix
#' @export
median_filter_cpp <- function(image, radius) {
    .Call(`_CaImagingAnalysisFr_median_filter_cpp`, image, radius)
}

#' Threshold image (C++ implementation)
#'
#' @param image Numeric matrix
#' @param threshold Threshold value
#' @param method "binary", "otsu", or "adaptive"
#'
#' @return Binary integer matrix
#' @export
threshold_image_cpp <- function(image, threshold, method = "binary") {
    .Call(`_CaImagingAnalysisFr_threshold_image_cpp`, image, threshold, method)
}

#' Shift image by given displacement (C++ implementation)
#'
#' Fast image shifting using bilinear interpolation.
#'
#' @param image Numeric matrix representing the image
#' @param shift_x X displacement (can be fractional)
#' @param shift_y Y displacement (can be fractional)
#'
#' @return Shifted image matrix
#' @export
shift_image_cpp <- function(image, shift_x, shift_y) {
    .Call(`_CaImagingAnalysisFr_shift_image_cpp`, image, shift_x, shift_y)
}

#' Compute phase correlation between two images
#'
#' Fast phase correlation for motion estimation.
#'
#' @param ref Reference image matrix
#' @param target Target image matrix
#' @param max_shift Maximum allowed shift
#'
#' @return NumericVector with c(shift_x, shift_y, correlation)
#' @export
phase_correlation_cpp <- function(ref, target, max_shift) {
    .Call(`_CaImagingAnalysisFr_phase_correlation_cpp`, ref, target, max_shift)
}

#' Motion correct entire movie
#'
#' Apply motion correction to all frames efficiently.
#'
#' @param movie 3D array (height x width x frames)
#' @param template Reference image
#' @param max_shift Maximum shift
#'
#' @return List with corrected movie and shifts
#' @export
motion_correct_movie_cpp <- function(movie, tmpl, max_shift) {
    .Call(`_CaImagingAnalysisFr_motion_correct_movie_cpp`, movie, tmpl, max_shift)
}

#' Compute template by averaging frames
#'
#' @param movie 3D array
#' @param n_frames Number of frames to average (0 = all)
#'
#' @return Template image matrix
#' @export
compute_template_cpp <- function(movie, n_frames = 0L) {
    .Call(`_CaImagingAnalysisFr_compute_template_cpp`, movie, n_frames)
}

