name: R-CMD-check
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y r-cran-testthat
      - name: Install package
        run: R CMD INSTALL .
      - name: Run tests
        run: R -q -e 'testthat::test_dir("tests/testthat")'
